#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex269_HBridge, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           motor2,        tmotorVex269_MC29, openLoop, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool button1_pushed; //flag to store button1 input
bool button2_pushed; //flag to store button2 input


/* monitorInput()
*
*  Used to flag button inputs
*       - this avoids errors caused by program recognizing input, taking action, and
*         reading input again before button is released
*/
void monitorInput()
{
	if(SensorValue(button1) && !button1_pushed)
	{
		button1_pushed = true;
	}

	if(SensorValue(button2) && !button2_pushed)
	{
		button2_pushed = true;
	}
}





void MoveForwards(int TargetDistance, int Speed){
	int motor1Pos = getMotorEncoder(motor1);
	int motor2Pos = getMotorEncoder(motor2);
	motor[motor1] = Speed;                    //Turn on both motors
	motor[motor2] = Speed;

	if(motor1Pos >= TargetDistance){         //When Target distance is reached, Cut motors
		motor[motor1] = 0;
		motor[motor2] = 0;
		button1_pushed = false;
	}
}

void Turn(int TargetArc, int Speed){     //Positive TargetArc is CounterClockwise. motor1 = Left, Motor2 = Right
	int motor1Pos = getMotorEncoder(motor1);
	int motor2Pos = getMotorEncoder(motor2);
	motor[motor1] = Speed;
	motor[motor2] = -Speed;

	if(motor1Pos >= TargetArc){
	motor[motor1] = 0;
	motor[motor2] = 0;
	button2_pushed = false;
	}
}









void exercise_3()
{
	enum T_test_state{          //Initialize 3 states
		stopped = 0,
		forward,
		backward,
	};
	T_test_state exer3_state = stopped;     //Set initial state to "stopped"
	while(true)
	{
		monitorInput();


		/* INSERT CODE HERE
		* - make sure EXERCISE_NUMBER is set to 3
		*/

		switch(exer3_state){

		case stopped:                            //Stopped Case

			motor[motor1] = 0;                     //Set speed to 0
			resetMotorEncoder(motor1);             //Zero the motor encoder
			if(button1_pushed == true){
				exer3_state = forward;               //Change state to forward when button 1 pushed
				button1_pushed = false;              //debounce button1
			}
			if(button2_pushed == true){
				exer3_state = backward;             //Change state fo backwards when button 2 pushed
				button2_pushed = false;							//debounce button2
			}

			break;

		case forward:
			motor[motor1] = 50;										//Set motor speed to 50

			if(button1_pushed == true){
				button1_pushed = false;             //If button 1 is pushed again, disregard
			}

		/*	if(button2_pushed == true){
				//check this out
				exer3_state = backward;
			}*/

			if(getMotorEncoder(motor1) >= 3000){      //When the motor position <= 3000

				if(button2_pushed == true){
					exer3_state = backward;               //When forwards motion is complete, go backwards
					button2_pushed = false;               //Debounce button 2
					}else{
						exer3_state = stopped;              //If no other input, set state to stopped

						button1_pushed = false;             //Debounce button1
				}

				resetMotorEncoder(motor1);
			}
			button1_pushed = false;
			break;

			case backward:

			motor[motor1] = -50;                      //Spin motor backwards
			if(button2_pushed == true){
				button2_pushed = false;                 //If button 2 is pushed again, disregard
			}

			if(getMotorEncoder(motor1) <= -3000){     //Spin until motor position is -3000
				if(button1_pushed == true){
					exer3_state = forward;                //When backwards motion complete, go forwards
					button1_pushed = false;               //Debounce button 1
				}else{
					exer3_state = stopped;                //If no other input, set state to stop
				}
				resetMotorEncoder(motor1);
			}
			button2_pushed = false;                   //Debounce button2
			break;

		}

	}//end while

}//end exercse_3



task main()
{
	if(button1_pushed){
		MoveForwards(1000, 50);
	}

	if(button2_pushed){
		Turn(1000, 50);
	}


}
