#pragma config(Motor,  port3,           motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motor2,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motor1] = 50;
	motor[motor2] = 50;


}
