#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code will test your VEX controller.
// Connect the following devices to your VEX controller:
// 1. Button to VEX digital port 1.
// 2. Button to VEX digital port 2.
// 3. Two pin motor to VEX motor port 1.
// Tabs on side of connectors should fit into slots on side of ports.

// Ensure that platform is set to VEX 2.0 Cortex:
//    1. Select Robot->Platform Type->VEX Robotics->VEX 2.0 Cortex
// Update firmware:
//    1. Select Window->Menu Level->Super User
//    2. Select Robot->Download Firmware->Automatically Update VEX Cortex
// Run code
//    1. Click "Compile Program" button.
//    2. Click "Download to Robot" button
//    3. Click "Start" button in "Program Debug" window.
//    4. Hitting button connected to digital port 1 should cause motor to start.
//    5. Hitting button connected to digital port 2 should cause motor to stop.
// While code is running, you can repeat steps 4 and 5 as often as you need.

task main()
{
	while (1) {

	  motor[motor1] = 0;

		while ( SensorValue[button1] == 0 );

		motor[motor1] = 50;

		while( SensorValue[button2] == 0 );

		motor[motor1] = 0;
	}

}
